spring.application.name=desphub
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/desphub
spring.datasource.username=postgres
spring.datasource.password=desphub

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

rpa.base-url=http://localhost:8090
desphub.jwt.secret=56d5d5324d023790897a3efd16da840ecaeb10a513a288cb48d421aac573af30
desphub.jwt.expiration-minutes=480